/**
 * ResponsiveImage
 *
 * Loads pre-optimized AVIF + WebP variants generated by
 * `scripts/optimize-images.ts`. The `name` prop is the source basename
 * without extension or width (e.g., `hero-bg`).
 *
 * Hero images: pass `priority`. They get fetchpriority="high" and skip
 * lazy loading. All other images lazy-load with native browser support.
 *
 * The optimizer always emits a JPEG fallback at width 1200, so the
 * `<img>` element is always wired to that file.
 */

import type { CSSProperties, ReactElement } from "react";

export interface ResponsiveImageProps {
  name: string;
  alt: string;
  width: number;
  height: number;
  priority?: boolean;
  sizes?: string;
  className?: string;
  style?: CSSProperties;
  widths?: number[];
  fallbackWidth?: number;
}

const DEFAULT_WIDTHS = [400, 800, 1200, 1600];
const DEFAULT_FALLBACK_WIDTH = 800;

function buildSrcSet(name: string, ext: "avif" | "webp", widths: number[]): string {
  return widths.map((w) => `/images/optimized/${name}-${w}.${ext} ${w}w`).join(", ");
}

export function ResponsiveImage({
  name,
  alt,
  width,
  height,
  priority = false,
  sizes = "100vw",
  className,
  style,
  widths = DEFAULT_WIDTHS,
  fallbackWidth = DEFAULT_FALLBACK_WIDTH,
}: ResponsiveImageProps): ReactElement {
  const fallbackSrc = `/images/optimized/${name}-${fallbackWidth}.jpg`;

  return (
    <picture>
      <source type="image/avif" srcSet={buildSrcSet(name, "avif", widths)} sizes={sizes} />
      <source type="image/webp" srcSet={buildSrcSet(name, "webp", widths)} sizes={sizes} />
      <img
        src={fallbackSrc}
        alt={alt}
        width={width}
        height={height}
        loading={priority ? "eager" : "lazy"}
        decoding={priority ? "sync" : "async"}
        fetchPriority={priority ? "high" : "auto"}
        className={className}
        style={style}
      />
    </picture>
  );
}
